---
- hosts: webservers
  vars:
    site_path: "c:\inetpub\\wwwroot\mysite
		default_index_file: "index.html"
  tasks:
  - name: Ensure that IIS is installed
    win_feature:
	    name: "Web-Server"
	    state: present
	    restart: no
	    include_sub_features: no
	    include_management_tools: no
	  
   - name: Ensure the website directory is created
     win_file:
	     path: "{{ site_path }}"
	     state: directory
	   
  - name: Create sub iis site
    win_iis_website:
	    name: "RomLabs"
	    state: started
	    port: 8080
	    physical_path: "{{ site_path }}"
 
 - name: Copy default_index_file to site
   win_copy:
     src: "{{ default_index_file }}"
	   dest: "{{ site_path }}\\index.html"
	 
 - name: Ensure firewall rule is in place for site
   win_firewall_rule:
     name: RomLabs
	   enabled: yes
	   state: present
	   localport: 8080
	   action: allow
	   direction: in
	   protoccol: tcp
	