---
- name: Test Handlers
  hosts: server1
  tasks:
    - name: Install Dotnet 4.6.1
      win_chocolatey:
        name: dotnet4.6.1
        state: present
      notify:
        - reboot server

  handlers:
    - name: reboot server
      win_reboot: