---
- name: Join a Romlab domain
  hosts: all
  vars:
    domainname: ROMLAB.INTERNAL
    dnsname: romlab.internal
    domain_admin: cradmin@romlab.internal
  
  vars_prompt:
    - name: password
      prompt: "Enter domain admin credentials"


  tasks:
    - name: Joining the domaain "{{ domainname }}"
      win_domain_membership:
        dns_domain_name: "{{ dnsname }}"
        domain_admin_user: "{{ domain_admin }}"
        domain_admin_password: "{{ password }}"
        state: domain
      register: domain_state

    - name: Rebooting to join domain
      win_reboot: 
        msg: "Rebooting workstation/host..."
      when: domain_state.reboot.required